---
- name: Remove require tty
  lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent
- name: Remove require tty - alt
  lineinfile: regexp="requiretty" dest=/etc/sudoers.d/os_defaults state=absent

- lineinfile: state=present create=yes dest=/etc/sudoers.d/888-dont-requiretty line="Defaults !requiretty" backup=yes



